Add BaseXSendFileView
moggers87/django-sendfile2 pull request #4
Opened 2018-04-05 17:33 UTC by ad-m

2018-04-05 22:27 UTC, moggers87 requested changes
* There are errors from flake8 - you can run `tox -e flake8` to see them
* There are no tests

2018-04-05 22:27 UTC, moggers87 commented on sendfile/views.py
> +class BaseXSendFileView(BaseDetailView):
I don't think this is a base view, the only things I need to provide can be passed in via kwargs to `as_view`.

Also, a docstring explaining what `file_field` and `send_as_attachment` are would be good.

2018-04-05 22:28 UTC, moggers87 commented
Thanks for the PR. There are a couple of issues that I've highlighted in my review, but otherwise this looks good.

2018-04-25 08:31 UTC, moggers87 commented
@ad-m are you still working on this? There's no way I can merge this without tests.

2018-04-27 18:59 UTC, ad-m commented
I will not have time in the coming days. Adding tests to this code requires a significant extension of the tests, as currently no view is tested.

2018-07-13 09:53 UTC, moggers87 commented
Going close this now, feel free to re-open with tests.

2018-07-13 09:53 UTC, closed without merging